### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by rocammo** [TeamUbercube/ubercube#5]
I've successfully compiled **ubercube_server.jar** and **ubercube_client.jar**.
When I try to run them, server runs without problems, but after, when I run client, it throws the following exception:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
        at fr.veridiangames.client.MainComponent.main(MainComponent.java:41)
```
What I can do?

Thanks in advance.

**Comment by mploux** [comment]
You need to launch the game with arguments. You can see how to compile and launch in the readme [here](https://github.com/TeamUbercube/ubercube). I'm still going to add a usage message in case someone else forgets the arguments. 

Note: We didn't provide an executable for the moment as the game is still in development. Be aware that the game is not in active development anymore because we are all students and don't have the time, but we will hopefully continue soon.

Thanks for the report, and good day !
